# Generated by Django 4.2.8 on 2023-12-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flora_id', models.CharField(max_length=120)),
                ('species', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('evaluated_date', models.DateField()),
            ],
        ),
    ]
