# Generated by Django 4.2.8 on 2023-12-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(max_length=120)),
                ('altitude_range', models.CharField(max_length=120)),
                ('season', models.CharField(max_length=120)),
                ('soil', models.CharField(max_length=120)),
                ('flora_id', models.CharField(max_length=120)),
            ],
        ),
    ]
