# Generated by Django 4.2.8 on 2023-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0002_habitat'),
    ]

    operations = [
        migrations.CreateModel(
            name='characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('utility', models.CharField(max_length=120)),
                ('avail', models.CharField(max_length=120)),
                ('flora_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='marketValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('flora_id', models.CharField(max_length=120)),
                ('cons', models.CharField(max_length=120)),
                ('exp', models.FloatField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_id', models.CharField(max_length=50)),
                ('flora_s', models.CharField(max_length=100)),
                ('login_date', models.DateField()),
                ('t_in', models.TimeField()),
                ('t_out', models.TimeField()),
                ('v_id', models.CharField(max_length=100)),
            ],
        ),
    ]
