# Generated by Django 4.2.8 on 2023-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_characteristics_marketvalue_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='can_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flora_id', models.CharField(max_length=100)),
                ('v_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_id', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('psd', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='viewer_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
    ]
